#lang pollen

◊div['((id "doc"))]{
The study of electric charge in motion.

The flow of ◊em{net} charge through a conductor constitutes an ◊strong{electic current}.

The amount of net charge flowing through the area per unit time

                        ◊div['((class "current"))]{◊img['((src "https://bit.ly/2YvGSOF"))]}

For steady current,

                        ◊div['((class "current2"))]{◊img['((src "img-72ee77512f5e6f27.png"))]}

Unit of current is Ampere.

Electric current has both ◊strong{magnitude and direction,} yet it is a ◊em{scalar quantity}.

◊h3{Metallic Conductance}

The metal consists of large number of atoms,so it has large number of free electrons.The free electrons are in random
motion .There is no any preffered directions of motion.Thus there is no net flow of charge in any direction.

 ◊div['((class "current3"))]{◊img['((src "vector.png"))]}

When an electric field is applied the electrons are accelerated but they instantly and frequently collide with residue atom.
At each collision the electron starts a fresh random   thermal velocity for short period of time.

At last suffering from number of continous collision the velocity generated by the electrons due to electric field ◊img['((src "vectorE.png"))],
This average velocity of electron slows velocity ◊em{(in comparison of random velocity)} of electron is known as drift velocity, ◊img['((src "dri.png"))].

◊strong{Relaxation time}: The average time between two successive collision of an electron is called relaxation time(τ).

◊strong{Drift velocity}: Average velocity gained by the free electron of conductor is known as drift velocity.
◊div['((class "current7"))]{◊img['((src "drift-vel-formula.png"))]}
                   ◊pre{where, e= charge of electron}
                         ◊pre{   m= mass of electron}
                         ◊pre{   τ= relaxation time}
                         ◊pre{   E= Electric filed}

◊img['((src "drawing.png"))]

It is noted that the direction of conventional current established the assumption to the flow (+ve) charge in metal/conductor.

When source of E.M.F is applied across the conductor the potential difference is maintained across the length of conductor.
◊div['((class "current9"))]{◊img['((src "emf.png"))]}

Hence, electric current flowing through the conductor .i.e,
◊div['((class "current10"))]{◊img['((src "drift-velocity-prove1.png"))]}

                   ◊pre{where, n=number of electron in given per unit volume}
                         ◊pre{       e=charge of electron}
◊div['((class "current11"))]{◊img['((src "drift-velocity-prove2.png"))]}

◊pre{Also, ◊img['((src "drift-velocity2.png"))]}

◊div['((class "current13"))]{◊img['((src "currentdensity.png"))]}

Here, J is ◊em{current density}

Current density is defined as amount of current flowing through the conductor per unit cross sectional area.It is a ◊strong{vector quantity} 
}
◊a['((class "nav-left") (href "#")){prev}]
◊a['((class "nav-right") (href "#")){next}]


              






